//
// Todoey
//
// Created by SAP BTP SDK Assistant for iOS v9.0.4 application on 14/02/23
//

import Foundation

/// Localized strings used by Onboarding
class LocalizedStrings {
    
    enum AppDelegate {
        static let startDemoModeTitle = NSLocalizedString("keyDemoModeSelectedTitle", value: "Demo Mode", comment: "XTIT: Title of alert action that the demo mode is selected.")
        static let startDemoModeMessage = NSLocalizedString("keyDemoModeSelectedMessage", value: "The Demo mode with Offline OData is not implemented in the generated application.", comment: "XMSG: Message that the user selected the demo mode.")
        static let startDemoModeRestartTitle = NSLocalizedString("keyGoBackButtonTitle", value: "Go back", comment: "XBUT: Title of go back button.")
        static let urlNotSupportedTitle = NSLocalizedString("keyUrlNotSupportedAlertTitle", value: "Alert!", comment: "XTIT: Title of alert action that the url is not supported.")
        static let urlNotSupportedMessage = NSLocalizedString("keyUrlNotSupportedMessage", value: "This url is currently not supported.", comment: "XMSG: Message that the url is not supported.")
        static let verificationFailedTitle = NSLocalizedString("keyVerificationFailedAlertTitle", value: "Failed!", comment: "XTIT: Title of alert that the signature verification failed.")
        static let verificationFailedMessage = NSLocalizedString("keyVerificationFailedMessage", value: "The digital signature could'nt be verified.", comment: "XTIT: Message that the signature verification failed.")
        static let urlNotSupportedOKButtonTitle = NSLocalizedString("keyUrlNotSupportedOKButtonTitle", value: "Okay", comment: "XBUT: Title of ok button.")
    }

    enum Onboarding {
        static let welcomeScreenMessage = NSLocalizedString("keyWelcomeScreenMessage", value: "This application was generated by SAP BTP SDK Assistant for iOS" + " v9.0.4", comment: "XMSG: Message on WelcomeScreen")
        static let welcomeScreenStartButton = NSLocalizedString("keyWelcomeScreenStartButton", value: "Start", comment: "XBUT: Title of start button on WelcomeScreen")
        static let failedToLogonTitle = NSLocalizedString("keyErrorLogonProcessFailedTitle", value: "Failed to logon!", comment: "XTIT: Title of alert message about logon process failure.")
        static let retryTitle = NSLocalizedString("keyRetryButtonTitle", value: "Retry", comment: "XBUT: Title of Retry button.")
        static let resetTitle = NSLocalizedString("keyResetButtonTitle", value: "Reset", comment: "XBUT: Title of Reset button.")
        static let passcodeRetryLimitReachedTitle = NSLocalizedString("keyErrorPasscodeRetryLimitReachedTitle", value: "Passcode Retry Limit Reached!", comment: "XTIT: Title of alert action that the passcode retry limit has been reached.")
        static let passcodeRetryLimitReachedMessage = NSLocalizedString("keyErrorPasscodeRetryLimitReachedMessage", value: "Reached the maximum number of retries. Application should be reset.", comment: "XMSG: Message that the application shall be reseted because the passcode retry limit has been reached.")
    }
    
    enum OnlineOData {
        static let oDataServiceFailedMessage = NSLocalizedString("keyODataServiceFailedMessage", value: "OData service is not reachable, please onboard again.", comment: "")
        static let errorLoadingData = NSLocalizedString("keyErrorLoadingData", value: "Loading data failed!", comment: "XTIT: Title of loading data error pop up.")
    }

    enum OfflineOData {
        static let openingOfflineStoreMessage = NSLocalizedString("keyOpeningOfflineStoreMessage", value: "Opening offline store", comment: "XMSG: Message that the application is opening the offline store.")
        static let updatingLocalDataMessage = NSLocalizedString("keyUpdatingLocalDataMessage", value: "Updating local data", comment: "XMSG: Message that the application is updating the local data from the offline store.")
        static let uploadingLocalDataMessage = NSLocalizedString("keyUploadingLocalDataMessage", value: "Uploading local data", comment: "XMSG: Message that the application is uploading the local data to the offline store.")
        static let sendingOfflineStoreMessage = NSLocalizedString("keySendingOfflineStoreMessage", value: "Sending offline store", comment: "XMSG: Message that the application is sending the offline store.")
        static let synchronizingDataMessage = NSLocalizedString("keySynchronizingDataMessage", value: "Synchronizing Data", comment: "XMSG: Message that the application is Synchronizing Data.")
    }
    
    enum Model {
        static let myDayTaskListView = NSLocalizedString("keyMyDayTaskListView", value: "My Day", comment: "")
        static let tomorrowTaskListView = NSLocalizedString("keyTomorrowTaskListView", value: "Tomorrow", comment: "")
        static let taskListTitle = NSLocalizedString("keyTaskListTitle", value: "Title", comment: "")
        static let taskListColor = NSLocalizedString("keyTaskListColor", value: "Color", comment: "")
        static let taskListIsDefault = NSLocalizedString("keyTaskListIsDefault", value: "Default", comment: "")
        static let taskTitle = NSLocalizedString("keyTaskTitle", value: "Title", comment: "")
        static let taskCollection = NSLocalizedString("keyTaskCollection", value: "Collection", comment: "")
        static let taskPriority = NSLocalizedString("keyTaskPriority", value: "Priority", comment: "")
        static let taskDueDate = NSLocalizedString("keyTaskDueDate", value: "Due Date", comment: "")
        static let taskDueTime = NSLocalizedString("keyTaskDueTime", value: "Due Time", comment: "")
        static let taskIsPlannedForMyDay = NSLocalizedString("keyTaskIsPlannedForMyDay", value: "Add to My Day", comment: "")
    }
    
    enum TaskView {
        static let createTaskTitle = NSLocalizedString("keyCreateTaskTitle", value: "New Task", comment: "")
        static let editTaskTitle = NSLocalizedString("keyEditTaskTitle", value: "Task Details", comment: "")
    }
    
}
